### ISSUE TITLE
Unable to build with Chapel 1.22.1 and 1.22.0

### ISSUE THREAD

**Issue by lnikon** [pnnl/chgl#79]
Can't build any of unit tests inside chgl/test.

`$ chpl --version`
`> chpl version 1.22.1
Copyright 2020 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)`

Trying to build with the following command:
`$ chpl -M ../src --no-lifetime-checking --no-warnings GraphTest.chpl`

Getting following output:
`> GraphTest.chpl:5: error: Attempt to 'new' a function or undefined symbol`
`../src/BinReader.chpl:16: In function 'binToHypergraph':`
`../src/BinReader.chpl:32: error: Attempt to 'new' a function or undefined symbol`
`../src/BinReader.chpl:73: In function 'binToGraph':`
`../src/BinReader.chpl:89: error: Attempt to 'new' a function or undefined symbol`
`../src/Metrics.chpl:113: In function 'getVertexComponentMappings':`
`../src/Metrics.chpl:118: error: Attempt to 'new' a function or undefined symbol`
`../src/Metrics.chpl:119: error: Attempt to 'new' a function or undefined symbol`
`../src/Metrics.chpl:199: In function 'getEdgeComponentMappings':`
`../src/Metrics.chpl:202: error: Attempt to 'new' a function or undefined symbol`
`../src/Metrics.chpl:203: error: Attempt to 'new' a function or undefined symbol`
`../src/Generation.chpl:268: In function 'generateChungLu':`
`../src/Generation.chpl:306: error: Attempt to 'new' a function or undefined symbol`
`../src/Generation.chpl:464: In function 'generateBTER':`
`../src/Generation.chpl:494: error: Attempt to 'new' a function or undefined symbol`
`../src/Traversal.chpl:10: In iterator 'vertexBFS':`
`../src/Traversal.chpl:12: error: Attempt to 'new' a function or undefined symbol`
`../src/Traversal.chpl:25: In iterator 'vertexBFS':`
`../src/Traversal.chpl:27: error: Attempt to 'new' a function or undefined symbol`
`../src/Traversal.chpl:28: error: Attempt to 'new' a function or undefined symbol`
`../src/Traversal.chpl:28: error: Attempt to 'new' a function or undefined symbol`
`../src/Traversal.chpl:45: In iterator 'edgeBFS':`
`../src/Traversal.chpl:47: error: Attempt to 'new' a function or undefined symbol`
`../src/Traversal.chpl:60: In iterator 'edgeBFS':`
`../src/Traversal.chpl:62: error: Attempt to 'new' a function or undefined symbol`
`../src/Traversal.chpl:63: error: Attempt to 'new' a function or undefined symbol`
`../src/Traversal.chpl:63: error: Attempt to 'new' a function or undefined symbol`
`../src/Visualize.chpl:152: In function 'main':`
`../src/Visualize.chpl:153: error: Attempt to 'new' a function or undefined symbol`
`../src/WorkQueue.chpl:28: In iterator 'doWorkLoop':`
`../src/WorkQueue.chpl:29: error: Attempt to 'new' a function or undefined symbol`
`../src/WorkQueue.chpl:244: In initializer:`
`../src/WorkQueue.chpl:247: error: Attempt to 'new' a function or undefined symbol`
`../src/WorkQueue.chpl:249: error: Attempt to 'new' a function or undefined symbol`
`../src/WorkQueue.chpl:251: error: Attempt to 'new' a function or undefined symbol`
`../src/AggregationBuffer.chpl:187: In function 'readWriteThis':`
`../src/AggregationBuffer.chpl:188: error: Attempt to 'new' a function or undefined symbol`
`../src/AggregationBuffer.chpl:190: error: Attempt to 'new' a function or undefined symbol`
`../src/AggregationBuffer.chpl:192: error: Attempt to 'new' a function or undefined symbol`
`../src/AggregationBuffer.chpl:194: error: Attempt to 'new' a function or undefined symbol`
`../src/AggregationBuffer.chpl:196: error: Attempt to 'new' a function or undefined symbol`
`../src/AggregationBuffer.chpl:198: error: Attempt to 'new' a function or undefined symbol`
`../src/AdjListHyperGraph.chpl:441: In initializer:`
`../src/AdjListHyperGraph.chpl:432: error: 'Lock' undeclared (first use this function)`
`../src/AdjListHyperGraph.chpl:478: In function 'equals':`
`../src/AdjListHyperGraph.chpl:491: error: 'Utilities' undeclared (first use this function)`
`../src/BinReader.chpl:16: In function 'binToHypergraph':`
`../src/BinReader.chpl:62: error: 'ssize_t' undeclared (first use this function)`
`../src/Utilities.chpl:374: error: 'size_t' undeclared (first use this function)`
`../src/Utilities.chpl:375: error: 'c_int' undeclared (first use this function)`
`../src/Utilities.chpl:507: In iterator 'getLines':`
`../src/Utilities.chpl:508: error: 'iomode' undeclared (first use this function)`
`../src/Visualize.chpl:4: In function 'visualize':`
`../src/Visualize.chpl:4: error: 'Graph' undeclared (first use this function)`
`../src/Visualize.chpl:6: error: 'iomode' undeclared (first use this function)`
`../src/Visualize.chpl:43: In function 'visualize':`
`../src/Visualize.chpl:43: error: 'AdjListHyperGraph' undeclared (first use this function)`
`../src/WorkQueue.chpl:16: In iterator 'doWorkLoop':`
`../src/WorkQueue.chpl:16: error: 'TerminationDetector' undeclared (first use this function)`

### Update
Tried to build with Chapel 1.22.0 as described inside dependencies.
Got linker errors:
`/usr/bin/ld: /home/nikon/projects/chapel-1.20.0/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-cstdlib/hwloc/re2/fs-none/lib_pic-none/libchpl.a(chpl-comm.o):(.bss+0x10): multiple definition of `chpl_comm_diags_disable_flag'; /tmp/chpl-nikon-95422.deleteme/CHGLTest.tmp.o:(.bss+0x58): first defined here`
`/usr/bin/ld: /home/nikon/projects/chapel-1.20.0/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-cstdlib/hwloc/re2/fs-none/lib_pic-none/libchpl.a(chpl-comm.o):(.bss+0x20): multiple definition of `chpl_comm_diags_counters'; /tmp/chpl-nikon-95422.deleteme/CHGLTest.tmp.o:(.bss+0x0): first defined here`
`/usr/bin/ld: /home/nikon/projects/chapel-1.20.0/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-cstdlib/hwloc/re2/fs-none/lib_pic-none/libchpl.a(chpl-comm-diags.o):(.bss+0xc): multiple definition of `chpl_comm_diags_disable_flag'; /tmp/chpl-nikon-95422.deleteme/CHGLTest.tmp.o:(.bss+0x58): first defined here`
`/usr/bin/ld: /home/nikon/projects/chapel-1.20.0/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-cstdlib/hwloc/re2/fs-none/lib_pic-none/libchpl.a(chpl-comm-diags.o):(.bss+0x20): multiple definition of `chpl_comm_diags_counters'; /tmp/chpl-nikon-95422.deleteme/CHGLTest.tmp.o:(.bss+0x0): first defined here`
`/usr/bin/ld: /home/nikon/projects/chapel-1.20.0/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-cstdlib/hwloc/re2/fs-none/lib_pic-none/libchpl.a(chpl-comm-callbacks.o):(.bss+0x0): multiple definition of `chpl_comm_callback_counts'; /home/nikon/projects/chapel-1.20.0/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-cstdlib/hwloc/re2/fs-none/lib_pic-none/libchpl.a(comm-none.o):(.bss+0x0): first defined here`
`/usr/bin/ld: /home/nikon/projects/chapel-1.20.0/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-cstdlib/hwloc/re2/fs-none/lib_pic-none/libchpl.a(chpl-tasks-callbacks.o):(.bss+0x0): multiple definition of `chpl_task_callback_counts'; /home/nikon/projects/chapel-1.20.0/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-cstdlib/hwloc/re2/fs-none/lib_pic-none/libchpl.a(tasks-qthreads.o):(.bss+0x18): first defined here`
`collect2: error: ld returned 1 exit status`
`make: *** [/home/nikon/projects/chapel-1.20.0/runtime/etc/Makefile.exe:30: /tmp/chpl-nikon-95422.deleteme/CHGLTest.tmp] Error 1`
`error: compiling generated source`

**Comment by LouisJenkinsCS** [comment]
Please see branch containing partially complete conversions.
https://github.com/pnnl/chgl/tree/1.23-port


Sent from Samsung tablet.



-------- Original message --------

**Comment by mark-raugas** [comment]
Yes – CHGL currently only supports Chapel 1.20.

 

Also please be aware CHGL is research code that will not have the full performance you might expect in the distributed case.  It has been developed from 2018 to 2020 and is an effort that was useful in providing feedback to the Chapel language team at HPE Cray.  

 

Active CHGL development by our team is planned to end shortly.
